# Generated by Django 5.1.3 on 2025-09-19 14:05

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('payments', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferralTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название уровня (для админки)')),
                ('min_payment_amount', models.DecimalField(decimal_places=2, help_text='Бонус будет начислен, если сумма покупки равна или больше этого значения.', max_digits=10, unique=True, verbose_name='Минимальная сумма покупки реферала (руб)')),
                ('bonus_days', models.PositiveIntegerField(verbose_name='Бонусных дней для реферера')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Уровень реферального бонуса',
                'verbose_name_plural': 'Уровни реферальных бонусов',
                'ordering': ['min_payment_amount'],
            },
        ),
        migrations.CreateModel(
            name='ReferralBonus',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('bonus_days_awarded', models.PositiveIntegerField(verbose_name='Начислено бонусных дней')),
                ('awarded_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата начисления')),
                ('referral', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bonuses_received_for', to='users.user', verbose_name='Чья покупка (Реферал)')),
                ('referrer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bonuses_given', to='users.user', verbose_name='Кто получил бонус (Реферер)')),
                ('triggering_payment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='payments.payment', verbose_name='Платеж, активировавший бонус')),
            ],
            options={
                'verbose_name': 'Реферальный бонус',
                'verbose_name_plural': 'Реферальные бонусы',
                'ordering': ['-awarded_at'],
            },
        ),
    ]
