# Generated by Django 5.1.3 on 2025-09-19 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('support_link', models.URLField(default='https://t.me/your_support_username', help_text="URL-адрес для кнопки 'Поддержка' в главном меню бота.", verbose_name='Ссылка на поддержку')),
            ],
            options={
                'verbose_name': 'Тех. поддержка',
                'verbose_name_plural': 'Тех. поддержка',
            },
        ),
    ]
