# Generated by Django 5.1.3 on 2025-09-23 12:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BroadcastSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('broadcast_admin', models.ForeignKey(blank=True, help_text='Пользователь, который будет подтверждать или отклонять рассылки. Если не указан, рассылки не работают.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.user', verbose_name='Администратор для рассылок')),
            ],
            options={
                'verbose_name': 'Настройки рассылок',
                'verbose_name_plural': 'Настройки рассылок',
            },
        ),
    ]
