# Generated by Django 5.1.3 on 2025-09-23 12:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_broadcastsettings'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='broadcastsettings',
            options={'verbose_name': 'Админ для рассылок', 'verbose_name_plural': 'Админ для рассылок'},
        ),
        migrations.AlterField(
            model_name='broadcastsettings',
            name='broadcast_admin',
            field=models.ForeignKey(blank=True, help_text='Пользователь, который будет подтверждать или отклонять рассылки. Если не указан, рассылки не работают.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.user', verbose_name='Администратор для рассылок (id)'),
        ),
    ]
