# Generated by Django 5.1.3 on 2025-09-21 02:11

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectStats',
            fields=[
            ],
            options={
                'verbose_name': 'Статистика Проекта',
                'verbose_name_plural': 'Статистика Проекта',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('users.user',),
        ),
    ]
