# Generated by Django 5.1.3 on 2025-09-28 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('SUCCEEDED', 'Успешно'), ('PENDING', 'Ожидает'), ('CANCELED', 'Отменен')], default='PENDING', max_length=10, verbose_name='Статус'),
        ),
    ]
