# Generated by Django 5.1.3 on 2025-09-28 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vpn', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='total_paid',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Пополнено'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='trial_activated',
            field=models.BooleanField(default=False, verbose_name='2 дня активирован'),
        ),
    ]
