# Generated by Django 5.1.3 on 2025-09-21 02:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Broadcast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(help_text='Основной текст рассылки. Будет отправлен как есть или как подпись к медиафайлу.', verbose_name='Текст сообщения')),
                ('media_file', models.FileField(blank=True, help_text='Опциональный файл для отправки (фото, видео, документ, аудио).', null=True, upload_to='broadcasts/', verbose_name='Медиафайл')),
                ('media_type', models.CharField(blank=True, choices=[('PHOTO', 'Фото'), ('VIDEO', 'Видео'), ('DOCUMENT', 'Документ'), ('AUDIO', 'Аудио')], help_text='Необходимо указать тип, если вы прикрепили медиафайл.', max_length=10, null=True, verbose_name='Тип медиафайла')),
                ('scheduled_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Укажите дату и время, когда рассылка должна быть отправлена.', verbose_name='Запланированное время отправки')),
                ('status', models.CharField(choices=[('SCHEDULED', 'Запланировано'), ('SENT', 'Отправлено'), ('ERROR', 'Ошибка'), ('CANCELED', 'Отменена')], default='SCHEDULED', max_length=10, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('task_id', models.CharField(blank=True, editable=False, max_length=255, null=True, verbose_name='ID задачи Celery')),
            ],
            options={
                'verbose_name': 'Рассылка',
                'verbose_name_plural': 'Рассылки',
                'ordering': ['-scheduled_at'],
            },
        ),
    ]
