# Generated by Django 5.1.3 on 2025-09-23 12:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sender', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='broadcast',
            options={'ordering': ['-created_at'], 'verbose_name': 'Рассылка', 'verbose_name_plural': 'Рассылки'},
        ),
        migrations.RemoveField(
            model_name='broadcast',
            name='scheduled_at',
        ),
        migrations.RemoveField(
            model_name='broadcast',
            name='task_id',
        ),
        migrations.AlterField(
            model_name='broadcast',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Ожидает подтверждения'), ('APPROVED', 'Одобрено (в процессе)'), ('SENT', 'Отправлено'), ('CANCELED', 'Отклонено'), ('ERROR', 'Ошибка')], default='PENDING', max_length=10, verbose_name='Статус'),
        ),
        migrations.CreateModel(
            name='SentBroadcastMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.BigIntegerField(verbose_name='ID сообщения в Telegram')),
                ('sent_at', models.DateTimeField(auto_now_add=True, verbose_name='Время отправки')),
                ('broadcast', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to='sender.broadcast')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='broadcast_messages', to='users.user')),
            ],
            options={
                'verbose_name': 'Отправленное сообщение рассылки',
                'verbose_name_plural': 'Отправленные сообщения рассылки',
                'unique_together': {('user', 'message_id')},
            },
        ),
    ]
